In [3]:
# Command lets us use the python library pandas with an alias of 'pd'
import pandas as pd

# Create Data Frame (table) from csv file using its relative path
customers_dirty = pd.read_csv("../practice_csv_files/radius_customers_dirty.csv")

# Get the first five rows of the data frame
customers_dirty.head()

,customer_id,first_name,last_name,age,gender,city,state,income_bracket,occupation,customer_since,...,gear_ownership,eco_priority,budget_per_purchase,travels_for_outdoor,dog_owner,social_platforms,heard_about_radius,nps_score,satisfaction_score,shopping_preference
0,RS-57602,Benjamin,Miller,58.0,Prefer not to say,Missoula,MT,$75k-$100k,Chef,"Sep 27, 2015",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RS-88654,Deborah,Hernandez,31.0,Female,Bozeman,mt,$30k-$50k,Electrician,7/25/2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RS-32245,Barbara,Young,0.0,Male,Idaho Falls,ID,$30k-$50k,NaN,6/24/2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RS-41094,Samantha,Anderson,62.0,Female,Portland,OR,<$30k,Flight Attendant,4/4/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RS-51670,jennifer,Nguyen,47.0,Male,Cheyenne,wy,$50k-$75k,HR Manager,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Show the shape of the data. In this case 515 rows and 27 columns. Multiplying the two numbers we see we have 13,905 entries or values
customers_dirty.shape

(515, 27)

In [5]:
# Using the index-based selection operator, iloc, we get the last 5 rows (-5:) for the first 15 columns (0:15)
# In pandas it is row first, column second
customers_dirty.iloc[-5:, 0:15]

,customer_id,first_name,last_name,age,gender,city,state,income_bracket,occupation,customer_since,total_spend_usd,purchase_frequency_per_year,preferred_contact,email,phone
510,RS-91360,Emily,Nelson,-1.0,Non-binary,Idaho Falls,ID,$50k-$75k,NaN,2016-05-03,2188.97,7.0,text,emily_nelson@aol.com,(970) 824-8417
511,RS-80852,Emma,Green,51.0,Female,Burlington,VT,$75k-$100k,Teacher,12/01/2017,0.00,7.0,email,egreen@outlook.com,(534) 929-3940
512,RS-36523,Emily,Martin,37.0,Prefer not to say,burlington,VT,$30k-$50k,NaN,"Sep 22, 2021",974.00,9.0,Text,martine@yahoo.com,(812) 858-6186
513,RS-51738,Edward,Johnson,65.0,NaN,Concord,NH,$75k-$100k,Accountant,4/13/2022,NaN,5.0,Text,edward_johnson@outlook.com,(288) 502-6997
514,RS-62976,Angela,Smith,30.0,Prefer not to say,Fairbanks,AK,$75k-$100k,Optometrist,"Dec 6, 2018",324.97,15.0,phone call,angela38@aol.com,(479) 525-8905

In [6]:
# Using loc we get the first 15 rows for the columns, 'first_name', 'last_name', and 'age'
customers_dirty.loc[0:15, ['first_name', 'last_name', 'age']]

   first_name  last_name   age
0    Benjamin     Miller  58.0
1     Deborah  Hernandez  31.0
2     Barbara      Young   0.0
3    Samantha   Anderson  62.0
4    jennifer     Nguyen  47.0
5     Melissa      Davis  69.0
6      Donald      Lewis  23.0
7    Jennifer   Williams  61.0
8     Charles      Green  60.0
9      Steven    Johnson  66.0
10      Nancy   Anderson   NaN
11    Deborah  Hernandez  31.0
12    Michael     Nelson  47.0
13  Katherine     Carter  28.0
14   Nicholas   Campbell  56.0
15     Justin      Young  48.0

In [7]:
# We can use conditionals to get rows that correspond to what we are looking for. In this case using == and the % (and) operator we get
# rows in which the person's favorite activity is 'Cycling', and their age is over 20
customers_dirty.loc[(customers_dirty.favorite_activities == 'Cycling') & (customers_dirty.age > 20)]

,customer_id,first_name,last_name,age,gender,city,state,income_bracket,occupation,customer_since,...,gear_ownership,eco_priority,budget_per_purchase,travels_for_outdoor,dog_owner,social_platforms,heard_about_radius,nps_score,satisfaction_score,shopping_preference
32,RS-65057,William,Brown,22.0,Non-binary,Boulder,CO,$150k+,Firefighter,"Aug 22, 2022",...,Rent,No,under 50,No,NO,YouTube,Trade Show,6.0,5.0,Both
345,RS-72414,Kimberly,Torres,26.0,Female,Billings,MT,$50k-$75k,Electrician,10/11/2017,...,Own,NO,$150-$300,N,Y,None|TikTok,Email Campaign,4.0,5.0,In-Store
360,RS-30461,Sarah,Moore,69.0,Prefer not to say,Bozeman,MT,$150k+,Electrician,2019-01-24,...,OWNS,NO,$300-$500,No,Yes,Reddit|YouTube|Twitter/X,Email Campaign,7.0,4.0,Both
509,RS-86917,Donald,Taylor,39.0,Male,Eugene,Oregon,$75k-$100k,Pharmacist,2/21/2015,...,Own,NO,300-500,No,NO,YouTube|Reddit,Friend/Family Referral,8.0,2.0,Online

In [8]:
# We can use .isin to get the rows that correspond to a list of values we give. In this case those rows (people) that have an age of 22 or 26
# Not a range as it doesn't get values in between the two only 22 or 26
customers_dirty.loc[customers_dirty.age.isin([22.0, 26.0])]

,customer_id,first_name,last_name,age,gender,city,state,income_bracket,occupation,customer_since,...,gear_ownership,eco_priority,budget_per_purchase,travels_for_outdoor,dog_owner,social_platforms,heard_about_radius,nps_score,satisfaction_score,shopping_preference
19,RS-99861,Carol,Walker,26.0,Female,Portland,ME,<$30k,Construction Manager,09/25/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,RS-72146,Deborah,Brown,22.0,Non-binary,Boulder,Col.,$30k-$50k,Real Estate Agent,6/12/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,RS-65057,William,Brown,22.0,Non-binary,Boulder,CO,$150k+,Firefighter,"Aug 22, 2022",...,Rent,No,under 50,No,NO,YouTube,Trade Show,6.0,5.0,Both
37,RS-18802,Jeffrey,Lewis,26.0,Non-binary,OGDEN,Utah,<$30k,Pharmacist,"Jul 23, 2019",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,RS-62947,Pamela,Smith,22.0,Non-binary,Portland,OR,$100k-$150k,HR Manager,"Apr 25, 2022",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,RS-73156,Emily,Carter,22.0,Female,Cheyenne,WY,<$30k,Plumber,"Oct 13, 2019",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,RS-27038,Anna,Moore,26.0,NaN,BILLINGS,MT,$30k-$50k,Personal Trainer,"Aug 15, 2016",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,RS-22793,Maria,Martin,22.0,Female,PORTLAND,OR,$50k-$75k,Plumber,2020-02-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,RS-85992,Frank,Torres,22.0,Female,BOZEMAN,Mont.,$75k-$100k,Software Engineer,"Nov 3, 2015",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,RS-88660,Mary,Adams,26.0,Female,Salt Lake City,UT,$30k-$50k,Lawyer,2019-11-23,...,Rents,No,$300-$500,yes,N,TikTok|YouTube,Social Media,9.0,2.0,online
204,RS-33627,Margaret,Thompson,26.0,Non-binary,Ogden,UT,$150k+,Construction Manager,3/6/2021,...,Own,no,50 to 150,no,YES,YouTube,Google Search,1.0,3.0,Online only
205,RS-64519,Melissa,Campbell,22.0,Male,Ogden,UT,$30k-$50k,Chef,07/24/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,RS-60173,Stephanie,Sanchez,26.0,Prefer not to say,Boise,ID,$30k-$50k,NaN,2017-12-16,...,owns,NO,$500+,yes,N,Instagram,Trade Show,2.0,1.0,Both
235,RS-73253,Kimberly,Ramirez,26.0,Non-binary,Jackson,WY,<$30k,NaN,2015-08-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,RS-91968,Brandon,Baker,22.0,Non-binary,Portland,ME,$100k-$150k,Graphic Designer,"Nov 11, 2018",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,RS-33203,Christopher,Hernandez,22.0,Non-binary,Boise,ID,$50k-$75k,Nurse,3/1/2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,RS-59425,Pamela,Lopez,26.0,Non-binary,fairbanks,AK,$50k-$75k,Consultant,"Aug 11, 2020",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,RS-21248,Nancy,Mitchell,22.0,Prefer not to say,Bozeman,MT,NaN,Dentist,06/19/2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,RS-69589,Susan,Davis,26.0,NaN,colorado springs,CO,$100k-$150k,Doctor,2016-02-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,RS-41946,ryan,Torres,22.0,Prefer not to say,Reno,NV,$50k-$75k,Flight Attendant,2022-03-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,RS-72414,Kimberly,Torres,26.0,Female,Billings,MT,$50k-$75k,Electrician,10/11/2017,...,Own,NO,$150-$300,N,Y,None|TikTok,Email Campaign,4.0,5.0,In-Store
369,RS-64106,Melissa,Thompson,26.0,NaN,Denver,co,<$30k,Construction Manager,"Jan 5, 2015",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
391,RS-42638,Eric,Wilson,22.0,Female,Bend,OR,$150k+,Pilot,7/10/2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
406,RS-38687,Dennis,Lewis,26.0,Non-binary,Idaho Falls,ID,$50k-$75k,Accountant,10/11/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420,RS-32449,Barbara,Lee,26.0,NaN,COLORADO SPRINGS,CO,$150k+,Flight Attendant,"Oct 12, 2022",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,RS-76115,Deborah,Davis,22.0,Prefer not to say,MISSOULA,MT,$100k-$150k,Financial Advisor,2017-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# To see rows in which one column is not null we can use .notnull(). Here we see 111 rows in which a value is entered for their favorite activity
# The rest of the rows are ignored as they had null values in this column
customers_dirty.loc[customers_dirty.favorite_activities.notnull()]

,customer_id,first_name,last_name,age,gender,city,state,income_bracket,occupation,customer_since,...,gear_ownership,eco_priority,budget_per_purchase,travels_for_outdoor,dog_owner,social_platforms,heard_about_radius,nps_score,satisfaction_score,shopping_preference
32,RS-65057,William,Brown,22.0,Non-binary,Boulder,CO,$150k+,Firefighter,"Aug 22, 2022",...,Rent,No,under 50,No,NO,YouTube,Trade Show,6.0,5.0,Both
33,RS-30070,Anthony,Rivera,-1.0,Non-binary,Eugene,OR,$50k-$75k,Electrician,5/27/2018,...,Rents,no,$300-$500,yes,Y,None|Instagram,Friend/Family Referral,1.0,3.0,ONLINE
34,RS-41808,rachel,NELSON,47.0,Male,OGDEN,Utah,$50k-$75k,Data Analyst,3/11/2023,...,Owns,Yes,$150-$300,Yes,Y,None|Pinterest,Google Search,5.0,4.0,online
38,RS-69796,Carol,Harris,39.0,Prefer not to say,Boise,ID,$50k-$75k,Surveyor,"Sep 17, 2019",...,Own,YES,$150-$300,yes,Yes,Instagram|Twitter/X|YouTube,Trade Show,3.0,2.0,Both
43,RS-20793,Jennifer,Green,49.0,Non-binary,Portland,me,$50k-$75k,Nutritionist,12/10/2018,...,Owns,No,$150-$300,Yes,NO,TikTok,Friend/Family Referral,6.0,5.0,online
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,RS-50563,Janet,Johnson,24.0,Male,Asheville,NC,<$30k,Pharmacist,11/13/2022,...,Owns,Yes,$150-$300,N,YES,Instagram|None|TikTok,Friend/Family Referral,3.0,3.0,in-store
497,RS-54744,Paul,Williams,47.0,Female,Knoxville,TN,$100k-$150k,Social Worker,2022-12-14,...,Rents,YES,50 to 150,no,YES,Facebook,Friend/Family Referral,2.0,2.0,ONLINE
498,RS-82512,Mary,Hall,35.0,Non-binary,Portland,Oregon,$50k-$75k,Chef,11/10/2016,...,Rents,NO,$150-$300,No,NO,TikTok|None|Twitter/X,Podcast,9.0,2.0,in-store
509,RS-86917,Donald,Taylor,39.0,Male,Eugene,Oregon,$75k-$100k,Pharmacist,2/21/2015,...,Own,NO,300-500,No,NO,YouTube|Reddit,Friend/Family Referral,8.0,2.0,Online
513,RS-51738,Edward,Johnson,65.0,NaN,Concord,NH,$75k-$100k,Accountant,4/13/2022,...,RENTS,Sometimes,$50-$150,no,yes,TikTok,Online Ad,8.0,1.0,Online only

In [10]:
# Creating a simple data frame to observe we can change a column's existing values by doing df_name['column_name] = 'new value'
reviews = pd.DataFrame({'critic': ['no', 'yes']})
reviews['critic'] = 'everyone'
reviews['critic']

0    everyone
1    everyone
Name: critic, dtype: str

In [14]:
# We can get the first 6 rows (loc is inclusive therefore :5 means include row index 5) and get the specified columns for the rows
# Columns can be out of order. In the data frame first_name comes before age and gender, but here we can change the order
customers_dirty.loc[:5, ['age', 'gender', 'first_name']]

    age             gender first_name
0  58.0  Prefer not to say   Benjamin
1  31.0             Female    Deborah
2   0.0               Male    Barbara
3  62.0             Female   Samantha
4  47.0               Male   jennifer
5  69.0               Male    Melissa